# Generated by Django 6.0.7 on 2026-07-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdblistrr", "0002_secure_secret_lengths"),
    ]

    operations = [
        migrations.AddField(
            model_name="sonarrinstance",
            name="enable_queue_import",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sonarrinstance",
            name="is_library_source",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sonarrinstance",
            name="is_ondemand_target",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sonarrinstance",
            name="quality_profile",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sonarrinstance",
            name="root_folder",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
