# Generated by Django 6.0.7 on 2026-07-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdblistrr", "0003_sonarrinstance_enable_queue_import_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="radarrinstance",
            name="enable_queue_import",
            field=models.BooleanField(default=False),
        ),
    ]
