# Generated by MDBListarr duplicate cleanup feature
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('mdblistrr', '0004_radarrinstance_enable_queue_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonarrCleanupCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvdb_id', models.IntegerField()),
                ('target_series_id', models.IntegerField()),
                ('episode_file_id', models.IntegerField()),
                ('linked_episode_keys', models.JSONField(default=list)),
                ('reason', models.CharField(default='permanent_duplicate', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('deleted', 'Deleted'), ('cancelled', 'Cancelled'), ('already_absent', 'Already absent')], default='pending', max_length=32)),
                ('first_eligible_at', models.DateTimeField()),
                ('last_confirmed_at', models.DateTimeField()),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_candidates', to='mdblistrr.sonarrinstance')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sonarrcleanupcandidate',
            constraint=models.UniqueConstraint(fields=('target_instance', 'episode_file_id'), name='uniq_sonarr_cleanup_target_file'),
        ),
    ]
