# Generated by Django 6.0.7 on 2026-07-23 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdblistrr", "0005_sonarrcleanupcandidate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SonarrEpisodeSearchCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_series_id", models.PositiveIntegerField()),
                ("target_episode_id", models.PositiveIntegerField()),
                ("tvdb_id", models.PositiveIntegerField()),
                ("season_number", models.PositiveIntegerField()),
                ("episode_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("first_eligible_at", models.DateTimeField()),
                ("last_confirmed_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_search_candidates",
                        to="mdblistrr.sonarrinstance",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_instance", "target_episode_id"),
                        name="uniq_sonarr_search_target_episode",
                    )
                ],
            },
        ),
    ]
