# Generated by Django 6.0.7 on 2026-07-31 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdblistrr", "0006_sonarrepisodesearchcandidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="sonarrepisodesearchcandidate",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Total accepted submission attempts, including the initial attempt.",
            ),
        ),
        migrations.AddField(
            model_name="sonarrepisodesearchcandidate",
            name="retry_not_before",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sonarrepisodesearchcandidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("submitted", "Submitted"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="SonarrEpisodeSearchCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_series_id", models.PositiveIntegerField()),
                (
                    "sonarr_command_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitting", "Submitting"),
                            ("queued", "Queued"),
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("aborted", "Aborted"),
                            ("cancelled", "Cancelled"),
                            ("orphaned", "Orphaned"),
                            ("ambiguous", "Ambiguous"),
                            ("unavailable", "Unavailable"),
                            ("superseded", "Superseded"),
                        ],
                        default="submitting",
                        max_length=32,
                    ),
                ),
                (
                    "sonarr_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "sonarr_result",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("submission_attempted_at", models.DateTimeField()),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("terminal_at", models.DateTimeField(blank=True, null=True)),
                ("outcome_reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_fallback_checked_at", models.DateTimeField(blank=True, null=True)),
                ("unavailable_since", models.DateTimeField(blank=True, null=True)),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "retry_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retries",
                        to="mdblistrr.sonarrepisodesearchcommand",
                    ),
                ),
                (
                    "target_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_search_commands",
                        to="mdblistrr.sonarrinstance",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sonarrepisodesearchcandidate",
            name="current_command",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_candidates",
                to="mdblistrr.sonarrepisodesearchcommand",
            ),
        ),
        migrations.CreateModel(
            name="SonarrEpisodeSearchCommandCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_episode_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="command_links",
                        to="mdblistrr.sonarrepisodesearchcandidate",
                    ),
                ),
                (
                    "command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_links",
                        to="mdblistrr.sonarrepisodesearchcommand",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sonarrepisodesearchcommand",
            name="candidates",
            field=models.ManyToManyField(
                related_name="search_commands",
                through="mdblistrr.SonarrEpisodeSearchCommandCandidate",
                to="mdblistrr.sonarrepisodesearchcandidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="sonarrepisodesearchcommandcandidate",
            constraint=models.UniqueConstraint(
                fields=("command", "candidate"),
                name="uniq_sonarr_search_command_candidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="sonarrepisodesearchcommand",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sonarr_command_id__isnull", False)),
                fields=("target_instance", "sonarr_command_id"),
                name="uniq_sonarr_search_command_per_target",
            ),
        ),
    ]
