# Generated by Django 6.0.7 on 2026-08-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdblistrr", "0007_sonarrepisodesearchcandidate_attempt_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="radarrinstance",
            name="is_library_source",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="radarrinstance",
            name="is_ondemand_target",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="radarrinstance",
            name="quality_profile",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="radarrinstance",
            name="root_folder",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
