# Generated by Django 6.0.7 on 2026-08-02 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdblistrr", "0008_radarrinstance_is_library_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RadarrMovieSearchCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "radarr_command_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitting", "Submitting"),
                            ("queued", "Queued"),
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("aborted", "Aborted"),
                            ("cancelled", "Cancelled"),
                            ("orphaned", "Orphaned"),
                            ("ambiguous", "Ambiguous"),
                            ("unavailable", "Unavailable"),
                            ("superseded", "Superseded"),
                        ],
                        default="submitting",
                        max_length=32,
                    ),
                ),
                (
                    "radarr_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "radarr_result",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("submission_attempted_at", models.DateTimeField()),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("terminal_at", models.DateTimeField(blank=True, null=True)),
                ("outcome_reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_fallback_checked_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("unavailable_since", models.DateTimeField(blank=True, null=True)),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "retry_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retries",
                        to="mdblistrr.radarrmoviesearchcommand",
                    ),
                ),
                (
                    "target_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_search_commands",
                        to="mdblistrr.radarrinstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RadarrMovieSearchCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_movie_id", models.PositiveIntegerField()),
                ("tmdb_id", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("first_eligible_at", models.DateTimeField()),
                ("last_confirmed_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Total accepted submission attempts, including the initial attempt.",
                    ),
                ),
                ("retry_not_before", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_search_candidates",
                        to="mdblistrr.radarrinstance",
                    ),
                ),
                (
                    "current_command",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_candidates",
                        to="mdblistrr.radarrmoviesearchcommand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RadarrMovieSearchCommandCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_movie_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="command_links",
                        to="mdblistrr.radarrmoviesearchcandidate",
                    ),
                ),
                (
                    "command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_links",
                        to="mdblistrr.radarrmoviesearchcommand",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="radarrmoviesearchcommand",
            name="candidates",
            field=models.ManyToManyField(
                related_name="search_commands",
                through="mdblistrr.RadarrMovieSearchCommandCandidate",
                to="mdblistrr.radarrmoviesearchcandidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="radarrmoviesearchcandidate",
            constraint=models.UniqueConstraint(
                fields=("target_instance", "target_movie_id"),
                name="uniq_radarr_search_target_movie",
            ),
        ),
        migrations.AddConstraint(
            model_name="radarrmoviesearchcommandcandidate",
            constraint=models.UniqueConstraint(
                fields=("command", "candidate"),
                name="uniq_radarr_search_command_candidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="radarrmoviesearchcommand",
            constraint=models.UniqueConstraint(
                condition=models.Q(("radarr_command_id__isnull", False)),
                fields=("target_instance", "radarr_command_id"),
                name="uniq_radarr_search_command_per_target",
            ),
        ),
    ]
