# Generated by Django 6.0.8 on 2026-08-16 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mdblistrr",
            "0009_radarrmoviesearchcommand_radarrmoviesearchcandidate_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RadarrCleanupCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.PositiveIntegerField()),
                ("source_movie_id", models.PositiveIntegerField()),
                ("source_movie_file_id", models.PositiveIntegerField()),
                ("target_movie_id", models.PositiveIntegerField()),
                ("movie_file_id", models.PositiveIntegerField()),
                (
                    "source_edition",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "target_edition",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "reason",
                    models.CharField(default="permanent_duplicate", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("deleted", "Deleted"),
                            ("cancelled", "Cancelled"),
                            ("already_absent", "Already Absent"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("first_eligible_at", models.DateTimeField()),
                ("last_confirmed_at", models.DateTimeField()),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleanup_candidates",
                        to="mdblistrr.radarrinstance",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_instance", "movie_file_id"),
                        name="uniq_radarr_cleanup_target_file",
                    )
                ],
            },
        ),
    ]
