# Generated by Django 6.0.8 on 2026-08-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdblistrr", "0010_radarrcleanupcandidate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArrReconciliationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        choices=[("sonarr", "Sonarr"), ("radarr", "Radarr")],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_result_code", models.IntegerField(blank=True, null=True)),
                (
                    "last_outcome",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("success", "Success"),
                            ("partial_failure", "Partial Failure"),
                            ("failure", "Failure"),
                        ],
                        default="never",
                        max_length=32,
                    ),
                ),
                (
                    "last_message",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_counters", models.JSONField(default=dict)),
                (
                    "source_instance_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "target_instance_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("source_ok", models.BooleanField(blank=True, null=True)),
                ("target_ok", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
