# Generated by Django 6.0.8 on 2026-08-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdblistrr", "0011_arrreconciliationstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="radarrcleanupcandidate",
            name="target_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="radarrcleanupcandidate",
            name="target_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sonarrcleanupcandidate",
            name="target_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="sonarrcleanupcandidate",
            name="target_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
